# -*- coding: utf-8 -*-
"""deep_learning_teampj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwrvxDHrXD71_nWzVDFNprOVSoT3lxpx

## Setting
"""
import os
import shutil
import numpy as np
import torch
print(torch.__version__)

os.system('nvcc -V')
os.system('cd /home/videorighter/Deeplearning_teampj')
os.system('git clone https://github.com/Tony607/voc2coco.git')
os.system("python3.7 -m pip install 'git+https://github.com/facebookresearch/detectron2.git'")
os.system('git clone https://github.com/facebookresearch/detectron2.git')
os.system('pip install Pillow==7.2.0 pyyaml==5.3.1')
os.system('pip show detectron2')

"""## Folder split"""

xml_path = '/content/drive/Shareddrives/딥러닝팀프로젝트/data/annotations'
png_path = '/content/drive/Shareddrives/딥러닝팀프로젝트/data/images'

if not os.path.isdir(xml_path + '/train'):
  os.makedirs(xml_path + '/train', exist_ok=True)
if not os.path.isdir(xml_path + '/val'):
  os.makedirs(xml_path + '/val', exist_ok=True)

file_list = os.listdir(xml_path)
file_list = [file for file in file_list if file.endswith(".xml")]

np.random.shuffle(file_list)

train_name, val_name = np.split(np.array(file_list), [int(len(file_list)*0.8)])

train = [xml_path + '/' + name for name in train_name.tolist()]
val = [xml_path + '/' + name for name in val_name.tolist()]

# Copy-pasting images
for name in train:
  shutil.move(name, xml_path + '/train')

for name in val:
  shutil.move(name, xml_path + '/val')

train_list = os.listdir(xml_path + '/train')
val_list = os.listdir(xml_path + '/val')
png_list = os.listdir(png_path)
png_list2 = [x[:-4] for x in png_list]
train_list2 = [x[:-4] for x in train_list]
val_list2 = [x[:-4] for x in val_list]

for png_name in png_list2:
    if png_name in train_list2:
      shutil.copy(png_path + '/' + png_name + ".png", xml_path + "/train/" + png_name + ".png")
    elif png_name in val_list2:
      shutil.copy(png_path + '/' + png_name + ".png", xml_path + "/val/" + png_name + ".png")

train_list = os.listdir(xml_path + '/train')
val_list = os.listdir(xml_path + '/val')

xml_train_list = [file for file in train_list if file.endswith(".xml")]
xml_val_list = [file for file in val_list if file.endswith(".xml")]

png_train_list = [file for file in train_list if file.endswith(".png")]
png_val_list = [file for file in val_list if file.endswith(".png")]

print(len(xml_train_list))
print(len(xml_val_list))
print(len(png_train_list))
print(len(png_val_list))

os.system('python3.7 /home/videorighter/Deeplearning_teampj/voc2coco/voc2coco.py '
          '/home/videorighter/Deeplearning_teampj/data/annotations/train '
          '/home/videorighter/Deeplearning_teampj/data/annotations/train/train.json')
os.system('python3.7 /home/videorighter/Deeplearning_teampj/voc2coco/voc2coco.py '
          '/home/videorighter/Deeplearning_teampj/data/annotations/val '
          '/home/videorighter/Deeplearning_teampj/data/annotations/val/val.json')
